const express = require('express');
const authRouter = require('./auth/auth.router');
const errorController = require('./shared/error.controller');
const ticketRouter = require('./ticket/ticket.router');
var cors = require('cors');
const app = express();
app.use(cors());
app.use(express.json());
app.use(authRouter);
app.use(ticketRouter);
app.use(errorController);
module.exports = app;
